### PR TITLE
feat(commit): added carrousel system with glide react

### PR DESCRIPTION
**Pull request by Gustavo-Espinoza**

### CODE REVIEW

**Review by Ditmar — APPROVED** [review]
Good PR, I like it. ok here you are the first approval

**Review by Ditmar — CHANGES_REQUESTED** [review]
we need to wait the approval of QA

**Comment by olmedo90** [comment]
image
 correct your imports and exports.

**Comment by olmedo90** [comment]
image
It is according to the assigned figma, continue with the same interest.
👍👍

**Review by Ditmar — APPROVED** [review]

**Pull request merged**
